Repository TeamDecisiontree/DecisiontreeProject, pull requests merged in 2025-05, with the labels that each got.

#142 Fixed path substring fix to make save files compatible with UNIX
  Game/Assets/Scenes/StartMenu/Scripts/NewGame.cs
Labels: bug

#146 UI fixes for Stats and Skilltree scenes
  Game/Assets/Scenes/SkillTree/AbilitiesWindow.unity
  Game/Assets/Scenes/SkillTree/Scripts/SkillButtonNode.cs
  Game/Assets/Scenes/Stats/Stats.unity
Labels: enhancement

#149 Enemies PRNG Update
  Game/Assets/Scenes/Combat/Scripts/Combat.cs
  Game/Assets/Scenes/Combat/Scripts/Enemy.cs
Labels: enhancement

#154 Add visible item stats in Shop
  Game/Assets/Scenes/Store/Scripts/ItemButton.cs
Labels: enhancement

#158 Fixed icons in skilltreetree and some skilltreetree design
  Game/Assets/Scenes/Combat/Scripts/Skills/Sacrifice.cs
  Game/Assets/Scenes/Cutscene/Sprites/intro/TheMiracle.png.meta
  Game/Assets/Scenes/SkillTree/AbilitiesWindow.unity
  Game/Assets/Scenes/SkillTree/Prefabs/HoverTooltip.prefab
  Game/Assets/Scenes/SkillTree/Prefabs/SkillButton.prefab
  Game/Assets/Scenes/SkillTree/Scripts/SkillButtonNode.cs
Labels: enhancement

#196 StatsList fix Mana to MaxMana
  Game/Assets/Scenes/Inventory/Scripts/StatsList.cs
Labels: bug

#206 Fixed text scaling in win/lose screen for gold/exp
  Game/Assets/Scenes/WinOrLoseScreen/DemoLoseScreen.unity
  Game/Assets/Scenes/WinOrLoseScreen/DemoWinScreen.unity
  Game/Assets/Scenes/WinOrLoseScreen/Scripts/WinLoseUpdate.cs
Labels: bug, enhancement

#210 Fixed issue #204 and made skill descriptions uniform
  Game/Assets/Scenes/Combat/Scripts/Skill.cs
  Game/Assets/Scenes/Combat/Scripts/Skills/Corrode.cs
  Game/Assets/Scenes/Combat/Scripts/Skills/Disarm.cs
  Game/Assets/Scenes/Combat/Scripts/Skills/MindControl.cs
  Game/Assets/Scenes/Combat/Scripts/Skills/Shield.cs
  Game/Assets/Scenes/Combat/Scripts/Skills/Zap.cs
Labels: enhancement

#211 Mini cleanup of debug logs
  Game/Assets/Scenes/Combat/Scripts/Skill.cs
  Game/Assets/Scenes/SkillTree/Scripts/SkillButtonNode.cs
Labels: enhancement

#215 Fix error in Map due to static class + meta
  Game/Assets/Scenes/Combat/Prefabs/Gladiator Boss.prefab.meta
  Game/Assets/Scenes/Map/Map.unity
Labels: bug
